---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - '--args=--sort-by required'
      - id: terraform_tfsec
      - id: terraform_providers_lock
