---
name: CI

on:
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        projects:
          - ''
          - 'examples/simple-repo/'
          - 'examples/json-files/'
          - 'examples/additional-claims/'
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: "./${{ matrix.projects }}"

  pre-commit:
    # We need to run on macos because the terraform provider lockfile checksums differ by architecture
    # terraform_providers_lock will fail on different architecture
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Install Brew Packages
        run: |
          # Need Bash 5 for terraform fmt in pre-commit hook
          # Nead realpath command for terraform_fmt which we get via coreutils
          brew install bash coreutils terraform-docs tfsec pre-commit

      - name: Run Pre-Commit
        run: pre-commit run --all-files
