---
name: CI

on:
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        projects:
          - ''
          - 'examples/simple-repo/'
          - 'examples/json-files/'
          - 'examples/additional-claims/'
          - 'test/prepare-server/'
          - 'test/configure-vault/'
          - 'test/configure-oidc/'
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: "./${{ matrix.projects }}"

  pre-commit:
    # Note that changing architectures will cause terraform_providers_lock to fail
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Install Brew Packages
        run: |
          # Need Bash 5 for terraform fmt in pre-commit hook
          # Nead realpath command for terraform_fmt which we get via coreutils
          brew install bash coreutils terraform-docs tfsec pre-commit

      - name: Run Pre-Commit
        run: pre-commit run --all-files

  e2e:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_wrapper: false

      - name: Run Tests
        run: make test
        env:
          TF_VAR_DO_token: ${{ secrets.DO_TOKEN }}
