---
name: CI

on:
  - pull_request

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        projects:
          - ''
          - 'examples/simple-repo/'
          - 'examples/json-files/'
          - 'examples/additional-claims/'
          - 'examples/github-enterprise/'
          - 'test/terratest/prepare-server/'
          - 'test/terratest/configure-vault/'
          - 'test/terratest/configure-oidc/'
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: "./${{ matrix.projects }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: "./${{ matrix.projects }}"

  lint-packer:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install Packer
        run: brew install packer

      - name: Initialize Packer
        run: packer init .
        working-directory: test/packer

      - name: Validate Template
        run: packer validate .
        working-directory: test/packer

      - name: Template Format Check
        run: packer fmt -check .
        working-directory: test/packer

  pre-commit:
    # Note that changing architectures will cause terraform_providers_lock to fail
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: test/go.mod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Install Brew Packages
        run: |
          # Need Bash 5 for terraform fmt in pre-commit hook
          # Nead realpath command for terraform_fmt which we get via coreutils
          brew install bash coreutils terraform-docs tfsec pre-commit

      - name: Run Pre-Commit
        run: |
          pre-commit --version
          pre-commit run --all-files
