---
name: End-to-End Tests

on:
  # Be very careful using this! Everything under this trigger should be locked behind an Environment Approval
  pull_request_target:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: E2E

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_wrapper: false

      - name: Run Tests
        run: make test
        env:
          TF_VAR_DO_token: ${{ secrets.DO_TOKEN }}
